- modules/bigeye/variables.tf
There is a public repo for images that aren't modified (mirrored). Use that one, the internal repo should be retired soon.
> style: use bigeye internal repo for dd image

- modules/bigeye/main.tf
The old CLI env vars are deprecated and need to be upgraded before we migrate to the new ubi primary images.
> feat: update temporal env vars to latest CLI

- .github/workflows/test_and_publish.yaml
- .gitignore
We don't want to deploy in parallel if there are several merges.
> fix: update deploy so mulitiple deploys run serially

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
toro is part of a legacy naming convention that does not need to be carried into the future
BREAKING CHANGE: Existing installs will need to set the `datawatch_rds_db_name = 'toro'` variable or the upgrade will destroy the application database will all application settings (including users etc).
> fix: use bigeye as the default mysql db name for the app db

- modules/bigeye/main.tf
The entrypoint for all services should be 80/443.  This is a bug fix as 7233 is the internal service port, but we are serving traffic on 443 via the LB so the SG should allow 443.
> fix: update temporal LB SG to allow 443

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/rds/main.tf
Adds several conditions and error messages for validating that users provide the necessary data when they are managing the security groups, namely when `create_security_groups` is false.
Fixes several places where `create_security_groups=false` was not being respected.
Adds an environment variable to scheduler so it can talk to itself on the traffic port (default `80`).
> Add validation messages and fixes

- modules/simpleservice/main.tf
We are waiting a long time before marking a node as healthy. Especially for background workers, this can result in unecessary ECS task termination.
Basically 5 x 90s = 7.5min before we mark a metricwork node as healthy again.
> fix: reduce time it takes to mark ECS nodes as healthy

- modules/bigeye/outputs.tf
This is useful for people to put into their datasource IP whitelists etc.  I didn't test it with BYO_VPC, but expect the depends_on to do the right thing
> feat: add NAT IPs to TF output

- modules/bigeye/main.tf
This will help keep important traffic off of public net (like ASM) as well as reduce ingress and egress costs for data transfers (like image pulls and ML models stored in s3).
There is a ~$8/mo per AZ charge for VPCe's so I opted not to add ones that are there just for the admin container debugging.  It's not critical for that traffic to stay off of private net anyhow.
> feat: add VPC endpoints for resources required for ECS

- modules/bigeye/main.tf
Use a standard set of subnet names that match the byovpc subnet variables to reduce confusion.  Overall these are easier to understand for new users
- public
- internal
- application
> fix: normalize subnet names

- examples/self-managed-mtls-certs/README.md
- examples/self-managed-mtls-certs/generate_self_signed_mtls_certs.sh
- examples/self-managed-mtls-certs/main.tf
- modules/bigeye/outputs.tf
This is an example install for BYO mTLS certs which includes a script to generate a set of self-signed certs that can be used for this purpose.
There is one actual module update, which is to output the ECS role ID as that is will need to be used by installers to grant AWS secrets manager (ASM) access to the mTLS certs stored in ASM.
> feat: add BYO mTLS certs example

- modules/bigeye/outputs.tf
These are generally useful for automating external operations such as VPC peering between the stack created VPC and another
> feat: add additional networking resources to module outputs

- examples/self-managed-mtls-certs/main.tf
This is a required field, so should be in the example
> docs: add top_level_dns_name to self-managed-mtls-certs example

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This sensitive variable was being passed in as an environment variable, causing terraform plan to be obscured.
BREAKING CHANGE: A new variable `datadog_agent_api_key_secret_arn` should be used instead of `datadog_agent_api_key`
Recommendation: Use an AWS SecretsManager secret to store your API Key and pass its ARN into `datadog_agent_api_key_secret_arn`.
Downtime: No
> fix!: remove datadog_agent_api_key variable

- modules/bigeye/outputs.tf
These are replaced by temporalui_* outputs.
BREAKING CHANGE: Outputs starting with `temporal_admin_` have been removed.
Recommendation: Use the new outputs starting with `temporalui_`
Downtime: No
> fix!: remove deprecated temporal_admin outputs

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This was a sensitive variable that wasn't marked sensitive.
BREAKING CHANGE: The `sentry_dsn` variable was removed
Recommendation: Use the `sentry_dsn_secret_arn` variable, passing the ARN to an AWS SecretsManager secret.
Downtime: No
Steps: Store your Sentry DSN in an AWS SecretsManager secret, delete the `sentry_dsn` terraform variable, and use the `sentry_dsn_secret_arn` variable instead.
> fix!: remove sentry_dsn variable

- modules/bigeye/main.tf
default for RDS mysql is MIXED and this poses problems for most dataloaders that want to sync incrementally.  ROW is preferred.
> feat: set binlog format to ROW

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- modules/rds/main.tf
- modules/rds/variables.tf
It's useful to be able to tag the primary and replica DB's with different tags.
> feat: allow separate optional tags for primary vs replica dbs

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This service can be quite verbose (and thus costly).  Add a flag to disable cloudwatch logging for this service if desired since the logs are rarely used.
> feat: add flag to control temporal logging

- .github/workflows/test_and_publish.yaml
This updates the runtime to node 20 so we don't get the node 16 warnings on GH action runs.
> fix: bump GH slack actions version

- examples/self-managed-mail-server/README.md
- examples/self-managed-mail-server/main.tf
- examples/self-managed-vpc-no-internet-access/README.md
- examples/self-managed-vpc-no-internet-access/main.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
commit da39491e3063ece27557b7dd429571a488953191 (HEAD -> matthalverson/one-1339-code-change-make-the-4-email-server-params-configurable, origin/matthalverson/one-1339-code-change-make-the-4-email-server-params-configurable)
Date:   Thu Feb 15 18:34:38 2024 -0800
docs: add documentation for byo mail server
commit d90425a9a706e27ab7a4900672b8425913db9d38
Date:   Thu Feb 15 18:12:45 2024 -0800
feat: add BYO mail server env vars to datawatch, datawork, metricwork
These vars are for plumbing in a custom SMTP server.  The app is
set up to fall back to default for both empty string env vars
and non-existant env vars.
I opted to only enable the feature if all 4 required env vars are
specified to avoid any kind of …
> Make the 4 email server params configurable

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- modules/rabbitmq/main.tf
- modules/rabbitmq/variables.tf
The usual method of allowing attachment of additional security groups to grant access does not work for Amazon MQ after MQ creation.  To side step this and still allow addtional access to Rabbit's AMQPS and HTTPS admin console, this PR allows passing in extra cidr blocks directly.
> feat: add ability to set ingress cidr blocks for rabbitmq

- modules/bigeye/main.tf
- modules/rabbitmq/main.tf
commit 5b2ee9a4670990cf3a745d21d44beeb832130562 (HEAD -> david/sre-2840-allow-access-to-rabbit-mq-admin-page-https-for-tf-stacks, origin/david/sre-2840-allow-access-to-rabbit-mq-admin-page-https-for-tf-stacks)
Date:   Thu Feb 22 16:51:50 2024 -0800
feat: allow admin container access to RabbitMQ
BREAKING CHANGE: This requires manual deletion of the <stack>-rabbitmq
instance.
AWS managed RabbitMQ does not allow changing security group membership
for RabbitMQ so the resource must be deleted manually first before
we can allow the admin container access to RabbitMQ.
commit 728e0b582b33e96450747fb1bb8a55fc01776628
Date:   Thu Feb 22 16:43:26 2024 -0800
fix: use dedicated ingress rule for rabbitmq security group …
> Allow access to rabbit mq admin page https for tf stacks

- .github/workflows/test_and_publish.yaml
This fixes the node 16 warning
> fix: upgrade slackapi/slack-github-action to v1.25.0

- .github/workflows/test_and_publish.yaml
The workflow that this GH action is calling has been renamed.
> ci: rename SDP github action

- modules/rabbitmq/main.tf
When create_security_groups = false, rabbitmq security group creation is failing.  This bug was introduced in 3.0.0 https://github.com/bigeyedata/terraform-modules/pull/141
> fix: only create ingress rule if create_security_groups = true

- modules/bigeye/locals.tf
The logic should be:
Always create the ACM cert if it isn't passed in.
So it shouldn't rely on DNS control at all since Bigeye requires an ACM cert for SSL on the LBs as we want to enforce HTTPS every where.
Right now the logic does not cover the case where nothing is set (ie all defaults) which is a bug introduced in 1.14.0
> fix: always ACM cert creation flag logic

- modules/rabbitmq/main.tf
This should not have been set to 433
> fix: update rabbitmq admin port to 443

- modules/bigeye/locals.tf
The logic is flipped here, the list we are keeping is a list of hardware types that are not supported for Performance Insights.
> fix: logic update for when to install RDS performance insights

- examples/self-managed-vpc-no-internet-access/README.md
- examples/self-managed-vpc-no-internet-access/ec2_bastion_example.tf
- examples/self-managed-vpc-no-internet-access/main.tf
- examples/self-managed-vpc-no-internet-access/outputs.tf
- examples/self-managed-vpc-no-internet-access/secrets_example.tf
- examples/self-managed-vpc-no-internet-access/simple_email_server_example.tf
- examples/self-managed-vpc-no-internet-access/subdomain_example.tf
- examples/self-managed-vpc-no-internet-access/vpc_example.tf
There are tons of new features now, update this set of instructions with a working end to end install.  Normal installs will only require what's in main.tf, but for the purpose of creating a functional end to end install, all of the addtional *_example.tf files have been added to create addtional resources necessary such as SES, Workmail, a bastion for SSH tunnel, etc.
> docs: update self-managed-vpc-no-internet-access instructions

- examples/self-managed-vpc-no-internet-access/ec2_bastion_example.tf
- examples/self-managed-vpc-no-internet-access/main.tf
- examples/self-managed-vpc-no-internet-access/simple_email_server_example.tf
- examples/self-managed-vpc-no-internet-access/vpc_example.tf
This currently relies on the networking routes/subnets to prevent external access.  We should also be restricting the security groups to only allow ingress/egress from the VPC cidr in this example to add a 2nd layer of protection to the security moat.
> docs: restrict IPs to local subnet in no-internet example

- examples/self-managed-vpc-no-internet-access/README.md
- examples/self-managed-vpc-no-internet-access/simple_email_server_example.tf
- examples/self-managed-vpc-no-internet-access/vpc_example.tf
A couple things in this PR that are subtle.
1. There is what I would call a bug with ECR privatelink that both an S3 gateway and S3 interface endpoint must be created or ECR image pulls will fail due to some portion of the request chain going out over public net (even though we don't even have a route to public net).
This is solved in our example TF by adding a S3 *Interface* VPCE and it specifically must have private_dns_only_for_inbound_resolver_endpoint set to false or the requests still end up resolving with a public IP and thus failing.
2. The terraform-aws-modules/vpc/aws//modules/vpc-endpoints version that we were using had a bug where private_dns_only_for_inbound_resolver_endpoint was not getting applied to the VPCE.  Updating to > 5.5.0 fixes that problem as well.
With these …
> docs: fix bug with no-internet vpc example and ECR privatelink

- modules/bigeye/main.tf
The app tag is nice for billing/search/etc and we should apply it to all resources related to services.  The one oddity will be shared resources that several services use.  We have been using datawatch as the app name for those historically, so should continue to do so for consistency.
> fix: add app tag for temporal, redis, rabbit

- modules/bigeye/main.tf
Scheduler is producing background work that should be sent to a background worker - datawork.
> fix: scheduler datawatch address to datawork

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- modules/rds/main.tf
- modules/rds/variables.tf
This is useful when upgrading mysql DB engines as the replica has to be updated before the primary.
> feat: allow setting replica DB engine version

- modules/bigeye/locals.tf
This should be an alltrue (ie flag must be on + DB in allowed hardware list) in order to be enabled.  Since coalesce accepts the first true, it is skipping the instance type validation.
> fix: update logic enabling performance insights on RDS

- modules/bigeye/variables.tf
- modules/rds/variables.tf
RDS Performance insights are inexpensive enough that it is recommended this is on for all databaess (where the hardware supports it).  The change in 3.11.1 fixed the logic for enabling only if the hardware is not in the blacklist, but ended up disabling performance monitoring by default. This fix turns it back on by default.
> fix: set default for performance insights back to true

- modules/bigeye/main.tf
This service is supposed to be dedicated to running lineage related work which is all brokered from temporal.
> feat: disable MQ workers for lineagework service

- modules/bigeye/variables.tf
- modules/opensearch/main.tf
commit 84710ca1c43a1fa55e724b25d8617f758c0f5bdd (HEAD -> david/sre-3304-opensearch-1-is-not-an-allowed-value-for, origin/david/sre-3304-opensearch-1-is-not-an-allowed-value-for)
Date:   Tue May 14 13:04:15 2024 -0700
fix: set opensearch data and master node types to the same
Mix and match between intel and Graviton is not allowed.  Keep these
the same.  Also auto_tune is not allowed for t3 instance types.
Closes SRE-3305
commit 669b3d56638b255d3e8024654e44582a47f3dbc5
Date:   Tue May 14 12:56:55 2024 -0700
fix: always use 3 opensearch zones if zone aware is enabled
Valid options are 2 or 3 (1 is not allowed, so is a bug currently).
We should always use the recommended 3, especially since we are
setting the …
> Fix default Opensearch zone awareness count

- modules/rds/main.tf
major_engine_version is a required parameter
> fix: add missing flag for replica option group

- modules/bigeye/temporal.tf
The random password that gets generated was occiasionally missing
some of the required chars, which fails opensearch password validation.
> fix: update password strength rules for generated opensearch password

- modules/opensearch/main.tf
This is a required arg to have set, no rollback seems reasonable to avoid a deployment when autotune is disabled, which should be rare.
> fix: update opernsearch autotune rollback setting

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- modules/simpleservice/main.tf
- modules/simpleservice/outputs.tf
- modules/simpleservice/variables.tf
Previously, every time terraform applied changes, it would reset the desired_count of autoscaled services to their initial value, regardless of what the application autoscaling setting was at.
BREAKING CHANGE: The resource name for the aws_ecs_service's in the simpleservice module have been changed to reflect whether the desired_count is controlled.
Recommendation: Use 'terraform state mv' command to move existing ECS resources into their respective new names.
Downtime: Yes, if you do not follow these upgrade steps. No, if you use the 'terraform state mv' commands outlined in these upgrade steps.
Steps: You should run a series of terraform state mv commands. These commands will tell Terraform that the AWS ECS Services already exist, and that they just use a different name now.
Depending …
> Do not control desired_count when autoscaling is enabled

- CHANGELOG.md
The generated message doesn't follow our formatting for breaking change entries.
> docs: beautify changelog entry for 6.0.0

- modules/admin/main.tf
- modules/admin/variables.tf
- modules/bigeye/main.tf
- modules/bigeye/temporal.tf
- modules/bigeye/variables.tf
- modules/simpleservice/containers.tf
- modules/simpleservice/variables.tf
Allow sending ECS logs via AWS firelens.  This opens the door for shipping logs to other log destinations besides Cloudwatch.
> feat: allow using firelens for ECS logs

- modules/admin/main.tf
- modules/admin/variables.tf
- modules/bigeye/efs.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/temporal.tf
- modules/bigeye/variables.tf
- modules/simpleservice/containers.tf
- modules/simpleservice/main.tf
- modules/simpleservice/variables.tf
This is useful for debugging, like in the case where we would want to persist some generated data on instance stop like a heap dump.
A single EFS volume for the entire stack was chosen instead of volume per service as ECS containers can only allow 1 EFS volume mount, so with a single mount, all of the various container's EFS data can be read from the bigeye-admin container.
EFS access point per service gives us logical separation of data between the different services, so each service can only read/write its own data (except the admin container which can mount the root "/" so will see them all).
Also note it is not possible to disable AZ redundancy by using "one zone" mode to save on costs as we run into problems with EFS mount points not existing in the various AZ's since we don't allow …
> feat: add ability to mount EFS volume in app containers

- modules/bigeye/main.tf
This can be useful.  Enabling this if the EFS mount is available is quite lazy and a little roundabout.
> feat: enable heap dump on OOM for some java services

- modules/bigeye/main.tf
This reverts commit cf4cf055d46fb86ad31586476d7f766dc786e4ae.
There are some undesirable side effects from this.  Go back to sending this traffic through datawatch until a dedicated internal API service is implemented.
> fix: revert send monocle and toretto traffic to datawork instead

- modules/admin/main.tf
- modules/admin/variables.tf
- modules/alarms/main.tf
- modules/alarms/variables.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/outputs.tf
- modules/bigeye/variables.tf
This service will handle intenal API requests.  This separates concerns of handling internal vs external requests on our API servers and will lead to better uptime and easier troubleshooting of user inititiated requests.
A followup task will route internal calls.  This gives installers a chance to install the service first before changing any call routing until the service is stable.
> feat: add private API service (papi) 1

- examples/self-managed-vpc-no-internet-access/main.tf
Cross region ECR pulls do not work for privatelink.  Update to pull images from the region the stack is being created in.
> fix: update no-internet-access example image region

- examples/self-managed-vpc-no-internet-access/bring-your-own/ec2_bastion_example.tf
- examples/self-managed-vpc-no-internet-access/bring-your-own/simple_email_server_example.tf
commit 918ae5c9938e8286e73c2329484130cc8f2170e5 (HEAD -> david/sre-3387-iqt-test-install-probs, origin/david/sre-3387-iqt-test-install-probs)
Date:   Tue Jun 4 16:39:32 2024 -0700
docs: dynamically generate AMI name for self-managed-vpc-no-internet-access
AMIs are Region specific, we need to generate the AMI dynamically
for this example so that deployments to regions other than
us-west-2 will be able to find the image.
commit b97208caf773749390bf575c2dc931e2da84856c
Date:   Tue Jun 4 16:37:35 2024 -0700
docs: fix smtp VPCE subnet list for self-managed-vpc-no-internet-access
Not all services have a VPCE in every AZ.  SES SMTP for example does
not exist in us-east-1.
Set this up to dynamically set the list of …
> Fix self-managed-vpc-no-internet-access example install problems

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
commit 66da40f0cc38b88efd0bc159f85aee010d7b8249 (HEAD -> david/sre-3473-roll-out-kms-flags, origin/david/sre-3473-roll-out-kms-flags)
Date:   Wed Jun 26 15:11:30 2024 -0700
fix: add permissions for datawatch ECS task to use KMS key
The policy to allow datawatch to use the KMS key was
missing.
commit 1aa302a5ff99671d0ece8f623c5061b50b08dd87
Date:   Wed Jun 26 14:43:55 2024 -0700
fix: don't reference KMS unless feature is enabled
The resources for this feature shouldn't be created or referenced
unless the flag is turned on.
They should also be passed to the app as normal env vars, not
as AWS secrets manager secrets.
> fix: datawatch KMS key fixups

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
commit 2067655b0361148239ce2a9d3fcd79181cbfb32d (HEAD -> david/sre-3475-autoscale-papi, origin/david/sre-3475-autoscale-papi)
Date:   Wed Jun 26 17:14:52 2024 -0700
feat: reduce Papi ECS service deregistration delay to 3 minutes
This service is responsible for handling what should be short lived
requests.  Having a long deregistration delay is not ideal for
autoscaling services as hung requests could stall scale-in.
commit c4f8c3ad42e23b462c1b80905646dee618eadfeb
Date:   Wed Jun 26 16:47:45 2024 -0700
feat!: autoscale papi service
This service fits naturally into a CPU autoscaling paradigm as it
should be a CPU bound service that ramps up CPU util as the number of
requests served by the individual instances …
> Breaking change: Autoscale papi service

- modules/bigeye/main.tf
This condition was breaking permissions for the datawatch ECS service to access the KMS key.
> fix: remove broken condition in kms policy

- modules/admin/main.tf
- modules/admin/variables.tf
- modules/alarms/main.tf
- modules/alarms/variables.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/outputs.tf
- modules/bigeye/variables.tf
papi (private api) ended up not being a popular name internally, so it is being renamed to internalapi.  It was a thought to support the existing variable names and avoid the breaking change, but it will keep the house much cleaner if we just take the breaking change and remove them.
BREAKING CHANGE: All variables with papi in the name need to be globally replaced with internalwatch.
> fix: rename papi service to internalapi

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
The job runners can consume too much cpu/mem as the defaults are for 200 parallel threads.  These environment variables allow fine grained control over all of the Temporal based work queues.
I opted for a generic name on the TF variables as the queue membership can be fluid and would become breaking changes if we moved queue subscription around to different services
> feat: add env vars to control job executor parallelism

- modules/bigeye/variables.tf
This is a chunky workflow that consumes too much CPU per node due with the default number of parallel threads (200).  5 ends up being between 1-2 CPU which is very reasonable for most installs.
> fix: reduce default value for scorecard refresh parallelism

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
As requested in bigeyedata/semantic-data-platform#14885
Fixes ONE-2704
> feat: new Temporal task queue monocle-invalidation

- modules/bigeye/main.tf
This is useful for forensics and debugging to retain the models longer than 1 month as some autothreshold problems can take a long time to surface.
> feat: change autothreshold S3 file expiration to 45 days

- modules/bigeye/variables.tf
This causes a rather massive hotspot if a flood of work comes in and leads to the metricwork service becoming unresponsive.  5 is a reasonable starting point for most installs.
> fix: reduce default max metric run workflow slots to 5

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
These datawatch dirivative services were all sharing the same variable, but each service operates differently so should have their own setting
> feat: allow setting JVM MaxRAMPercentage for each service

- modules/bigeye/variables.tf
80 is a more conservative number and is just a better starting place as a default as it more stable than 85%.
> fix: reduce datawatch and derivative service max JVM ram percent

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This memory leak fix is experimental and the flag allows us to roll back without a code change.
> feat: add a feature flag to control a memory leak fix

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This flag is no longer needed, the memory leak fix is part of the code as of 1.65.0-hotfix.1 and os not configurable anymore.
> chore: remove FF_JVM_MEMORY_LEAK_FIX_ENABLED environment variable

- modules/bigeye/main.tf
This is a new queue and the datawork service is the only one that should be processing the jobs from this queue.
> fix: exclude issue-root-cause from lineagework service

- README.md
- modules/bigeye/main.tf
There is a new feature in datawatch and related services to allow an include list.  Using this removes the maintenance task of needing to maintain the exclude list everytime a new queue is added to temporal.
Also convert metricwork over to use this instead of the single queue override.  That feature is (or should be) deprecated and removed since we now have an include list.
This shouldn't be merged until 1.71.0 is released.
> feat: use an include queue list instead of exclude queue

- modules/admin/main.tf
- modules/admin/variables.tf
- modules/alarms/main.tf
- modules/alarms/variables.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/outputs.tf
- modules/bigeye/variables.tf
This service will be dedicated to handle the heavy catalog indexing queue to try and isolate the work and get memory and instance overloading under control.  For now we will start with just the dataset_index_op_v2 queue.
Rollout plan:
1. Launch with 0 instances
2. Update internal deployment tooling to handle the new service
3. Turn up instance count which will migrate the jobs to the new service
> feat: add indexwork service

- modules/bigeye/main.tf
Metricwork should only be running jobs from a single Temporal queue. This flag to disable MQ queues on metricwork was accidentally removed in a previous PR.
> fix: remove metricwork MQ workers

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This is an MQ based service so lends itself naturally to autoscaling.
Catalog indexing is not a real-time operation so autoscaling down to 0 when the queue is empty is ideal
> feat: autoscale indexwork service

- modules/bigeye/variables.tf
2 is an efficient number for most self-hoted installs and will be able to service requests in a reasonable time for several thousand tables.
> feat: reduce default indexwork instance count

- README.md
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This PRis removing the feature flags to control if indexwork is on or not.  It is just on going forward.
Catalog indexing is a CPU intensive process that is quite bursty in nature.  As such it has been moved to a dedicated service for resource isolation and hardware efficiency.  Note that the service will autoscale down to 0 instances when the queue is empty.  This is normal.
BREAKING CHANGE: The following feature flags will need to be removed from your config if you are using them:
- indexwork_enabled
- indexwork_autoscaling_enabled
> feat!: rollout indexwork service

- modules/bigeye/main.tf
Metric runs should all go to a single service - metricwork.
I don't think this makes any material changes, but is good to keep the house orderly.
> fix: update queue membership for MQ based metric runs

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This is an experimental flag to allow isolation of lineage MQ based work onto the lineagework service.
Not recommended for production.
> feat: add flag to migrate lineage MQ work to lineagework

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
commit 901c8938113955ee6512dbe429ccd60e2a29e7c9 (HEAD -> david/sre-3860-indexwork-hardware-tuning, origin/david/sre-3860-indexwork-hardware-tuning)
Date:   Mon Nov 4 14:44:15 2024 -0800
feat: increase datawatch default cpu
This service tends to be hungry and the setting affects UI and
API performance.  2CPU is a good starting point for most installations
commit 8e0efaf1be646d5274d26cbea6891a144bf2e3be
Date:   Mon Nov 4 14:40:48 2024 -0800
feat: scale indexwork in faster
Scale out ignores the cooldown so will happen whenever a new
message shows up on the queue, but we can scale-in faster by having
a shorter cooldown.
After some observation we have quite a few periods where there are
very small numbers of jobs …
> Indexwork hardware tuning

- modules/bigeye/variables.tf
This service is only used for installs with the Linege feature enabled.  This is very specific and requires additional hardware, so at this time, the lineagework service should come up disabled (with no instances running) to save on hardware costs
> feat: disable lineagework service by default

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This change has been vetted and is ready for 100% rollout so the feature flags are being removed.
The following queues will migrate off of datawork:
- lineage MQ queue will be serviced from lineagework
- catalog_index_v2 MQ queue will be serviced from indexwork
BREAKING CHANGE:
The following bigeye module variables have been removed:
- migrate_lineage_mq_queue_enabled
- migrate_catalog_indexing_mq_queue_enabled
Remove these from your configuration before upgrading to this version of the Bigeye terraform module.  If these have not been set before, no action is required.
> feat!: roll out lineage and catalog indexing queue migrations

- README.md
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
Some jobs are being terminated inflight during scale-in for this service.  Disabling autoscaling for this service is the safest route forward until this is resolved.
> fix!: disable autoscaling for indexwork service

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This change adds a variable that configures indexwork autoscaling feature.
Backward compatible: yes
> feat: make indexwork autoscaling configurable via variable

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
commit 18f12c6c46e8f0d8898aa62013fab7643064971a (HEAD -> david/sre-3953-move-indexingv1-temporal-task-queue-to-indexwork, origin/david/sre-3953-move-indexingv1-temporal-task-queue-to-indexwork)
Date:   Mon Nov 25 18:27:11 2024 -0800
feat: move indexing.v1 temporal queue to indexwork service
Indexwork is a dedicated worker service to handle catalog indexing
operations, this queue was missed when migrating the others.
Closes SRE-3953
commit 41419f1ac41390bd62f7dfc6e0d74949bc25e89c
Date:   Mon Nov 25 18:19:03 2024 -0800
style: use variables for temporal queue membership
This follows the pattern used for MQ queues and reduce typos.
> move indexing.v1 temporal task queue to indexwork

- README.md
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
commit fd178cc7103bbfb08e60574e249b39a6b672cebf (HEAD -> david/sre-3975-increase-the-base-instance-count-for-internalapi-to-more, origin/david/sre-3975-increase-the-base-instance-count-for-internalapi-to-more)
Date:   Wed Dec 4 15:49:38 2024 -0800
feat!: normalize target autoscaling variable names
monocle is also a target scaling service.  Make the variables look
the same as internalapi.
BREAKING CHANGE:
The following vars have been removed:
- var.monocle_autoscaling_enabled
- var.monocle_max_count
- var.monocle_autoscaling_request_count_target
- var.indexwork_autoscaling_enabled
The following vars have been added:
- var.monocle_autoscaling_min_capacity
- var.monocle_autoscaling_max_capacity
- var.monocle_autoscaling_type
- …
> allow alb reqest count per target autoscaling for internalapi

- README.md
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
During scale-in some backfill tasks can be terminated early which results in work loss.  Hard pinning the instance count for now avoids this.
BREAKING CHANGE:
- var.backfillwork_autoscaling_max_count has been removed
> fix!: remove autoscaling from backfillwork

- modules/bigeye/variables.tf
This service now also needs to run for self-hosted installs, set the default instance count to 1.
Closes SRE-4025
> feat: set lineagework instance count to 1

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
Allow controlling parallelism of this queue.  The max activity account looks strange (4), but this matches what is in the code.
Closes SRE-4020
> feat: allow setting issue-root-cause temporal client settings

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
These two queues are the last ones.  We will want to be able to restrict them as the default is 200 (200 threads!) and this causes some thrashing on datawork.
> feat: allow control of temporal parallelism remaining queues

- modules/rabbitmq/main.tf
Starting with 3.13, AWS requires auto minor version upgrade to be enabled.  This also has to be set _before_ trying to upgrade to 3.13.  So it is just best to set it to true now.
If someone has not touched the default already, leave it set to false.  It will get turned on when they upgrade to 3.12.x anyways and that is required before they upgrade to 3.13 as it is not possible to upgrade from 3.11.x -> 3.13 directly.
https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-version-management.html
> feat: enable auto minor version upgrade for rabbitmq

- README.md
- modules/bigeye/main.tf
There is a bug with the aws_mq_broker provider that does not handle auto version upgrades properly.  It is resolved as of 5.68.0
See: https://github.com/hashicorp/terraform-provider-aws/issues/38930
This is in preparation for AWS removing support for all versions of rabbit MQ < 3.13 and at version 3.13, they will hard control the patch revisions.
It is recommended to set var.rabbitmq_engine_version to "3.13". 3.13 will become the default for this module after AWS removes support for 3.12.x sometime in the first half of 2025 (currently scheduled for March)
BREAKING CHANGE:
If your installhas the "hashicorp/aws" provider version pinned to something lower than 5.68.0, increase the version to at least 5.68.0 and run `terraform init -upgrade`.
> fix!: increase minimum hashicorp/aws version to 5.68.0

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This flag just controls weather a trace id is logged in the response log from the backend server.  It will be set on (flag control removed) in Bigeye app version 2.2.0 anyways, so we are enabling this across the board in the terraform ahead of the code being released.
This variable will be removed in a future release.
> feat: enable datawatch_request_body_logging_enabled everywhere

- modules/alarms/variables.tf
These services should be run at high system utilization for efficiency, so this alarm should not be enabled on them as we are specifically looking to have high mem utilization on these services.
> fix: disable worker service mem util alarms

- modules/bigeye/variables.tf
The existing defaults are far too large.  These settings control the number of threads so hundreds of extra threads were being created which is not efficient.
The remaining settings that are not set to 2 will likely be revisited again sometime in the future.
> fix: update default temporal client parallelism settings

- modules/bigeye/variables.tf
2 can end up blocked if there are long queries, especially if data source is queuing queries due to stress
> fix: increase parallism for trigger-batch-metric-run activity queue

- modules/bigeye/cloudfront.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
Using a CDN is a standard technique to improve UI performance for requests from latency distant regions.
The caller will pass in both the S3 logging bucket and ACM cert to use with Cloudfront as they are likely to already exist for enterprise installs.
> feat: add option to use Cloudfront in front of the app

- modules/bigeye/cloudfront.tf
It is common practice to skip inspecting headers and query params for caching of static objects as it keeps the cache as speedy as possible.  This PR is doing that by assuming based on filename which objects are static and can bypass cache control.
Without this there are far more cache misses than expected.
> feat: improve Cloudfront caching strategy

- modules/bigeye/variables.tf
The older versions are EOL in AWS.  This is the recommended version for customers and matches what is run in Bigeye's production environments.
> feat: update default rabbitmq and mysql versions

- modules/bigeye/lineageplus.tf
- modules/bigeye/variables.tf
- modules/solr-single-instance/main.tf
- modules/solr-single-instance/variables.tf
Added new vars:
- `var.lineageplus_solr_opts` - allows to specify any arguments to be passed to the solr startup script
-  `var.lineageplus_solr_desired_count` - allows stopping solr without deleting the service.
> feat: add new lineageplus_solr variables

- modules/bigeye/cloudfront.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
The current implementation routed all requests through CF.  For API calls in particular this can be a problem as CF has rather short timeouts for API requests.
This creates a separate URL that the app can use just for requesting static assets from Cloudfront.
Other updates in this commit:
- introduce a 2nd flag to allow enable/disable of Cloudfront without a brief outage due to a race between DNS changes and cloudfront distribution creation/deletion
- allow setting Cloudfront request timeout
- set Cloudfront changes to wait for deploy.  This avoids a race with DNS changes when enabling/disabling cloudfront that will lead to downtime (routing to Cloudfront before it has been deployed)
> fix: update dns to only route static assets to cloudfront

- modules/bigeye/cloudfront.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
I missed pushing these changes up before merging
https://github.com/bigeyedata/terraform-modules/pull/425
- add https:// prefix to static asset root
- fix the non-Cloudformation root for static assets to just be the top level address instead of referencing haproxy
> fix: add https:// prefix to static asset root

- modules/bigeye/cloudfront.tf
Some of our JS files come from the static.* address.  Since one of those requests a CSS file, Cloudfront also needs to set the Access-Control-Allow-Origin header for files from static so CORS is allowed.
> fix: update CORS response headers for Cloudfront

- modules/bigeye/cloudfront.tf
These are not allowed currently and will get blocked during preflight requests for CORS
> fix: allow OPTIONS calls for Cloudfront

- modules/bigeye/delete_in_the_next_major_version.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/moved.tf
- modules/bigeye/outputs.tf
- modules/bigeye/temporal.tf
- modules/simpleservice/main.tf
- modules/simpleservice/outputs.tf
- modules/simpleservice/variables.tf
This will unify DNS CNAME management and will reduce the amount of copy-pasted resources required to add a new service.
> refactor: move route53 records management in simpleservice module

- modules/rds/delete_in_the_next_major_version.tf
- modules/rds/main.tf
- modules/rds/outputs.tf
this change makes rule order irrelevant
Details:
- moved old `aws_security_group` and `aws_vpc_security_group_ingress_rule` in `delete_in_the_next_major_version.tf
` file without changes.
This is to make sure that we don't have any race conditions during the apply
- added `_v2` suffix to the new resources and replaced `count` with `for_each` where applicable
> feat: use for_each instead of count for security group rules

- modules/rds/delete_in_the_next_major_version.tf
- modules/rds/main.tf
this resource was forgotten in the https://github.com/bigeyedata/terraform-modules/pull/444
> fix: preserve aws_security_group.db_replica_clients resource

- modules/bigeye/lineageplus.tf
- modules/solr-single-instance/main.tf
- modules/solr-single-instance/variables.tf
solr was not getting tags.  Also normalize the solr submodule's input variable names so they match the other services.
> fix: fix missing tags for ECS solr instance

- modules/rds/delete_in_the_next_major_version.tf
- modules/rds/main.tf
- modules/rds/outputs.tf
This reverts commit 4c73c3552dc922bbd97f0bca7724651235289a38.
for_each does not work when module is applied from scratch.
Fixes this error
> The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
> fix: revert "feat: use for_each instead of count for security group rulse

- modules/solr-single-instance/containers.tf
- modules/solr-single-instance/main.tf
We want to account for the side car containers and not try to use too much mem.  Doing so drives up cpu util drastically
> fix: calculate solr heap size based on container mem

- modules/simpleservice/containers.tf
This are quite spammy and can rack up the cloudwatch bill unnecessarily.
> fix: disable firelens console logs

- modules/solr-single-instance/containers.tf
- modules/solr-single-instance/main.tf
90% of OS is a floating value based on instance size, but really the OS overhead of the kernel + ECS things should be a fixed value.
256 is likely the right number, but 512 is a safe starting place for solr since we need this layer to be as stable as possible since it is the database for the lineageplus application.
Closes SRE-4444
> fix: use a flat value for OS overhead for solr mem calculation

- modules/rds/main.tf
This is useful for billing queries etc to have the DB tags on the snapshots
> feat: copy RDS instance tags to snapshots

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
No actual services are being migrated through the new ALB in this PR.
This is the first step to consolidating the internal load balancers into 1 and using path based routing instead of load balancer per service.
This is a cost savings step as each LB is ~$23/mo and it adds up with so many internal services.
Future PRs will migrate the services over and remove the dedicated per-service ALBs.
> feat: add a dedicated general purpose internal load balancer

- .github/workflows/test_and_publish.yaml
We no longer publish our source to S3 for consumption.  There was a customer that needed all dependencies pre-packaged (ie could not download terraform modules/deps from public net), but they no longer need this.
Disable this to avoid wasted work
> fix: remove publish bundle step from CI deploy

- README.md
- modules/simpleservice/main.tf
This is the first step in a 2 part series to migrate from inline security group rules to dedicated rules.  The inline rules do not track AWS rule Ids properly which blocks seamless changes.
Part 1 sets the inline rule to an empty list.  Without this, the old rules are left dangling and will conflict with new rules.
Part 2 is to remove the inline rules completely to avoid the inline rules fighting with the dedicated ingress/egress rules for control
BREAKING CHANGE: Part one should only be applied 1x.  Then upgrade to part 2 and the plan will be idempotent again.
> feat!: migrate off of inline security group rules part 1/2

- README.md
- modules/simpleservice/main.tf
BREAKING CHANGE: Part one should only be applied 1x.  Then upgrade
to part 2 and the plan will be idempotent again.
Closes SRE-4838
> feat!: migrate off of inline security group rules part 2/2

- .github/workflows/hook_update_image_tag.yaml
- .github/workflows/publish_bundle_s3.yaml
- .github/workflows/test_and_publish.yaml
- .github/workflows/test_commitlint.yaml
- .github/workflows/validate_docs.yaml
- .github/workflows/validate_github_actions_workflows.yaml
- .github/workflows/validate_shell_script_syntax.yaml
commit 7e956b4d6788688f1206224b7acfe2fec4818cd9 (HEAD -> david/sre-4859-terraform-modules-publish-version-failed-in-gh-action, origin/david/sre-4859-terraform-modules-publish-version-failed-in-gh-action)
Date:   Thu Apr 24 15:09:32 2025 -0700
fix: fix busted publish GH action
This action isn't working after https://github.com/bigeyedata/terraform-modules/pull/485/files
The changelog needs git checkout.  Overall the premise of running
the changelog in its own step was completely unncessary, so I
put it back to fix the error and have used the output from within
the publish step to drive the notification jobs instead.
commit b50fc511803b7c76976a174eb9575544ecdfc972
Date:   Thu Apr 24 14:53:29 2025 -0700
fix: pin …
> fix: pin sha for all github actions and fix publish GH action

- .github/workflows/test_and_publish.yaml
This bug was introduced in https://github.com/bigeyedata/terraform-modules/pull/499
The slack action upgrade was a major semver update which required a different interface
> fix: update slack action formatting

- modules/bigeye/deprecated.tf
- modules/bigeye/main.tf
commit fe5ac2eb4a5d502780061bbe269a13f96734d30a (HEAD -> david/sre-4836-add-internal-lb-route-for-haproxy, origin/david/sre-4836-add-internal-lb-route-for-haproxy)
Date:   Mon Apr 28 17:08:48 2025 -0700
chore: remove unused haproxy env vars
These are old env vars that are no longer in use.
commit 4f872988cfca386786d7a246fb561f08e6dbaf46
Date:   Mon Apr 28 17:31:54 2025 -0700
feat: add env var to control routing of Lineage API requests
This is allows migrating lineage API calls to the dedicated lineageapi
service via feature flag so it can be controlled differently on
various installs.
> feat: add env var to control routing of Lineage API requests

- modules/bigeye/deprecated.tf
- modules/bigeye/main.tf
This is an experiment to measure behavior with these unnecessary flags turned on, to see if it has an impact on cpu util
> feat: add flag to disabled unused datadog flags for monocle

- modules/alarms/main.tf
- modules/bigeye/main.tf
These two services were not part of the original migration, but are getting migrated now.
> feat: migrate datawatch and web to internal load balancer

- modules/solr-single-instance/main.tf
- modules/solr-single-instance/variables.tf
The OS root EBS volume can get uncomfortably full 
at 30GB because solr logs are quite high volume.
We are also missing tags on the OS EBS volume
> feat: increase solr os ebs volume size and fix ebs tags

- modules/bigeye/lineageplus.tf
- modules/bigeye/variables.tf
Only the solr data volume is configurable externally right now, plumb through the OS volume size as well.
> feat: allow setting solr OS root volume EBS volume size

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This was incorrectly set to 60s which is "short" for some requests on large installations.  900s is supposed to be our default to allow for some legacy synchronous API calls.
> fix: increase internal LB timeout to 900s

- modules/bigeye/temporal.tf
Queue age and Depth are useful tools for determining scaling.
These stats have been available via the prometheus endpoint on Temporal for the last couple revs.  Datadog themselves do not make these stats available natively (at this time), but the "extra_metrics" tag is available to indexing custom stats like this.
This will incur costs as a custom metric for self-hosted installations using Datadog.
> feat: add temporal queue depth and age to datadog stats

- modules/bigeye/lineageplus.tf
- modules/bigeye/variables.tf
- modules/solr-single-instance/containers.tf
- modules/solr-single-instance/variables.tf
This also allows setting the value.  These logs tend to be low value and high volume.  Allow setting this and change the default to be less verbose
> feat: change default for lineageplus solr log level to warn

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- modules/simpleservice/main.tf
- modules/simpleservice/variables.tf
Anomaly mitigation is a newer routing feature on ALB which ideally solves both hot spots due to large requests as well as avoiding the case where a sick instance (like with a broken DB connection) can get a large percentage of inbound requests routed to it because it processes them very quickly and thus has the "least number of active connections".
This isn't available in conjunction with session stickiness so is not used on the frontend, but will set this everywhere else.
BREAKING CHANGE: The aws provider version upgrade is required in order to control the enable flag for this feature.
> feat: allow enabling alb anomaly mitigation

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
This can be disabled or set to target tracking, but is set to cpu_scaling by default.  30% has been a reliable balance between cost and slow scale out time and overall helps the system cope with the occasionally overly large request that can come in.
Note the service will be replaced if you don't intervene and this will cause an outage
Run this before running terraform apply to avoid the service replacement. tf  state mv 'module.bigeye.module.datawatch.aws_ecs_service.controlled_count[0]' \ 'module.bigeye.module.datawatch.aws_ecs_service.uncontrolled_count[0]'
> feat: add CPU autoscaling for datawatch

- README.md
- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- Adds cpu autoscaling to web and haproxy services
- sets 30% cpu target as the default for autoscaling as 65 was a little slow to react since request counts can be sparse
> feat: normalize autoscaling config for api/ui facing services

- modules/bigeye/main.tf
- modules/bigeye/variables.tf
- modules/simpleservice/main.tf
- modules/simpleservice/variables.tf
This is for cost savings to leverage spot instances for ECS
where possible without impacting reliability.  Spot instances
are not reclaimed often in ECS and when they are it is typically
in a single AZ, so instances will simply redeploy to a different
AZ.
There is one setting across the board vs per service settings to
keep things tidy.
NOTE that the solr service for LineagePlus is ommitted from spot
instances as it does not tolerate node re-deployment without
an interruption in service.
> feat: allow using fargate spot instances

- modules/bigeye/main.tf
- modules/bigeye/temporal.tf
LB deregistration delay and instance stop time need to finish before the 2 minute grace period that is given when spot instances are terminated.  IF the LB deregistration delay runs beyond that, we will end up with an instance that is terminated, but still registered in the LB, which could lead to some dropped requests.
Some services have long running tasks or do not tolerate being restarted frequently as well so those are pinned to not use spot instances.
Closes SRE-4347
> fix: adjust spot instance configs

- modules/bigeye/main.tf
The static asset root should be set to the vanity url when Cloudfront is not in use.
Putting this behind the var.cloudfront_route_static_asset_traffic flag was missed in a previous PR.  What can happen is that during a blue/green deploy, static assets will 404 since session stickiness will not be respected if the STATIC_ASSET_ROOT does not match the main vanity url.
> fix: use vanity url for static assets when CDN is disabled

- modules/bigeye/main.tf
These jobs can run longer than 2 minutes so are not a good candidate for spot instances due to potential for loss of work.
> fix: disable spot instances for metricwork

- modules/alarms/deprecated.tf
- modules/alarms/main.tf
- modules/bigeye/deprecated.tf
- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/simpleservice/data.tf
- modules/simpleservice/main.tf
- modules/simpleservice/outputs.tf
- modules/simpleservice/variables.tf
This consolidation effort is a house cleaning effort to reduce the number of LBs for privatelink agents installs
commit 8ba9a47691d7e7187a6be8f9e111e0e6b07e4cde (HEAD -> david/external-lb-part2, origin/david/external-lb-part2)
Date:   Tue Jul 1 11:15:45 2025 -0700
feat: add flags to migrate to centralized external LB
These are cutover flags and the associated cleanup tasks
required to apply clean.
Deploy strategy to avoid a service interruption:
1) terraform apply as-is - this will create the centralized external
loadbalancer and target group
2) add var.use_centralized_external_lb = true and run terraform apply
again.  This will cutover to using the centralized external LB
3) add var.install_individual_external_lbs = false.  This will
delete the …
> feat: add dedicated LB for external calls into Bigeye

- .github/workflows/test_and_publish.yaml
This flag is deprecated and doesn't do anything anymore.
> fix: skip sending previous version to triggered deploy job

- modules/bigeye/deprecated.tf
- modules/bigeye/lineageplus.tf
- modules/bigeye/variables.tf
- modules/solr-single-instance/main.tf
- modules/solr-single-instance/variables.tf
The metacenter address is legacy, but must continue to be supported as existing lineageplus customers are using it.
1) There is no reason to use a CNAME in one place, but an alias record in another, let's consolidate and use the same record for all aliases
2) The external LB was missing the legacy metacenter hostname based routing rule
> fix: fix metacenter-solr access

- modules/opensearch/main.tf
This service did not have AWS tags applied which are useful for billing/accounting/management.
> fix: add missing tags for opensearch service

- modules/bigeye/locals.tf
- modules/bigeye/main.tf
- modules/s3/main.tf
The agent large payload bucket is actually a general purpose bucket and some of the lineage processing jobs do clean up after themselves.
We also want to add object versioning to have a record of mutations for forensics.
> fix: update S3 perms and add object versioning

- modules/bigeye/variables.tf
3 is the minimum redundancy count for API/UI systems so there is still redundancy if there is 1 failure.  It is still possible
to adjust these numbers lower, but the default now is for 3.
> fix: adjust minimum ECS task count for api/ui services

- modules/bigeye/lineageplus.tf
- modules/bigeye/main.tf
- modules/bigeye/temporal.tf
- modules/simpleservice/main.tf
- modules/simpleservice/variables.tf
- modules/solr-single-instance/variables.tf
This is just house keeping.  The submodules no longer need the LB vars since the LBs have been centralized.
Ref SRE-5937
> fix: remove unused internal lb variables
