bigeyedata/terraform-modules

modules/bigeye/locals.tf
For consistencies sake, let's use the vanity_alias everywhere.
=> fix: use vanity_alias for all dns names

examples/minimal/README.md, examples/minimal/main.tf, examples/self-managed-ecr/README.md, examples/self-managed-ecr/get_bigeye_images.sh, examples/self-managed-ecr/list_bigeye_images.sh, examples/self-managed-ecr/main.tf, examples/self-managed-vpc/README.md, examples/standard/main.tf, modules/bigeye/main.tf
Most enterprise customers will want this after they get to first base.
```
$ ./list_bigeye_images.sh
{
"version": "0.0.0-brian",
"imagePushedAt": "2023-11-08T14:43:39-08:00"
}
{
"version": "0.0.0-brian-01",
"imagePushedAt": "2023-11-09T06:17:20-08:00"
}
{
"version": "0.0.0-brian-02",
"imagePushedAt": "2023-11-09T15:14:05-08:00"
}
{
"version": "0.0.0-brian-03",
"imagePushedAt": "2023-12-05T09:20:31-08:00"
}
{
"version": "1.32.0-hotfix.1",
"imagePushedAt": "2023-12-13T12:48:53-08:00"
}
{
"version": "1.32.0-hotfix.2",
"imagePushedAt": "2023-12-13T20:35:01-08:00"
}
```
=> docs: add example and instructions for BYO ECR repos

modules/bigeye/main.tf, modules/bigeye/variables.tf
Adds the ability to use an alternate image repository, e.g. for testing
=> feat: add an image repository suffix variable

modules/bigeye/main.tf
Comment the ports and order them sequentially for sanity.
=> chore: add comments to temporal ports

.github/workflows/test_and_publish.yaml, CHANGELOG.md, README.md, examples/minimal/main.tf, examples/self-managed-ecr/main.tf, examples/self-managed-vpc/main.tf, examples/standard/README.md, examples/standard/main.tf, scripts/replace-terraform-version.sh
Probably easiest to page thru the commits
=> Incorporate installation feedback

modules/bigeye/main.tf, modules/bigeye/variables.tf
This env var was deprecated and has now been removed from the app source.
=> fix: remove DEMO_ENDPOINT_ENABLED env var

examples/self-managed-vpc-no-internet-access/README.md, examples/self-managed-vpc-no-internet-access/main.tf, examples/self-managed-vpc-no-internet-access/vpc_example.tf, modules/bigeye/main.tf
This example is slightly different than the standard BYO VPC example
=> docs: add documentation and example for no-internet BYO VPC

modules/simpleservice/main.tf
This is so analyzing billing by tags works
=> feat: propagate ECS tags to the task

docs/TROUBLESHOOTING.md, modules/admin/main.tf, modules/admin/variables.tf, modules/bigeye/locals.tf, modules/bigeye/main.tf
=> Admin container fixes

modules/bigeye/main.tf
This setting will reduce lock contention for the application DB.
=> feat: set mysql transaction isolation to read-committed

modules/bigeye/locals.tf, modules/bigeye/main.tf, modules/bigeye/variables.tf
These knobs are useful to control throughput on the Temporal DB. https://docs.temporal.io/references/dynamic-configuration
=> feat: add control over temporal persistence QPS

modules/bigeye/main.tf, modules/bigeye/variables.tf, modules/simpleservice/outputs.tf
=> Fixes for monocle/toretto autoscaling

examples/self-managed-vpc-no-internet-access/README.md, examples/self-managed-vpc-no-internet-access/main.tf, examples/self-managed-vpc-no-internet-access/outputs.tf, examples/self-managed-vpc-no-internet-access/vpc_example.tf
Additional improvements/fixes to the example that were found after exercising the example a few more times.
=> docs: self-managed-vpc-no-internet-access doc updates

examples/self-managed-vpc-no-internet-access/simple_email_server_example.tf
We're using SMTP to publish messages to SES, this goes over a different port than the usual HTTP/HTTPS AWS APIs so the smtp VPC endpoint needs its own security group with that port open.
=> docs: fix smtp port for no internet example

modules/bigeye/main.tf, modules/bigeye/variables.tf, modules/rds/main.tf, modules/rds/variables.tf
This is useful for enabling things such as mysql audit logging.
=> feat: allow passing in rds db option group settings

modules/opensearch/main.tf
This is a bug currently for single node installs where availability_zone_count always shows as needing an update.
Using a dynamic config here just unsets it completely when not in use.
=> fix: use dynamic config for opensearch availability zone count

examples/self-managed-iam/README.md, examples/self-managed-iam/iam.tf, examples/self-managed-iam/main.tf, modules/admin/main.tf, modules/admin/variables.tf, modules/bigeye/locals.tf, modules/bigeye/main.tf, modules/bigeye/outputs.tf, modules/bigeye/temporal.tf, modules/bigeye/variables.tf
Variables have been added to allow IAM Roles to be passed into the
terraform module, rather than being managed by this module.
* ecs_service_role_arn
* admin_container_ecs_task_role_arn
* datawatch_task_role_arn
* monocle_task_role_arn
BREAKING CHANGE: This change required making the IAM resources
conditional. This results in an alteration to the resource address
in the terraform state file. If no manual action is taken, terraform
will try to destroy the IAM resources and recreate them in the new
address.
Recommendation: Run "terraform state mv" commands to move the
resources to their new address to avoid a destructive apply.
Downtime: If you do nothing - yes. If you follow these steps - no.
Steps: Run the following commands
```sh
terraform state mv \
'module.bigeye.aws_iam_role.ecs' \ …
```
=> Inject iam roles

modules/bigeye/locals.tf, modules/bigeye/main.tf, modules/bigeye/variables.tf
create resources for KMS encryption
=> feat: use KMS to encrypt secrets

modules/alarms/ecs/main.tf, modules/alarms/ecs/variables.tf, modules/alarms/main.tf, modules/alarms/variables.tf
It's a problem if a service has sustained high mem util and likely means it is time to scale up the hardware on that service
=> feat: add ECS mem util percent alarm

CHANGELOG.md
There are a few manual steps required to upgrade from 9.x.x to 10.0.0
=> docs: add instructions for upgrading to v10.0.0

modules/bigeye/variables.tf
See also https://github.com/bigeyedata/semantic-data-platform/pull/14630
=> Tune default reconciliation workflows pollers

modules/bigeye/main.tf
This method of using several autoscaling policies just leads to the two fighting for control over the number of instances.  Just use a cloudwatch metric that sums the message counts into a single metric instead
=> fix: update autoscaling for services scaling on multiple queues

README.md
I missed adding this in the PR for 13.0.0
=> docs: add instructions for upgrading to 13.0.0

modules/bigeye/variables.tf
These are the final values and are a sane default for most environments.
=> fix: update default temporal wf and exec counts to final values

modules/simpleservice/containers.tf
Reverts bigeyedata/terraform-modules#422
=> Revert "feat: add DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED env var"

modules/bigeye/lineageplus.tf, modules/solr-single-instance/main.tf
This will make it look like the others (app/component)
=> fix: normalize tags for solr service

modules/bigeye/lineageplus.tf, modules/bigeye/variables.tf
=> feat: make refresh_instance_on_launch_template_change configurable

modules/bigeye/variables.tf
This will save a few bucks, these backups are not high value to retain longer
=> feat: reduce temporal database default backup retention period

modules/solr-single-instance/containers.tf
There are requirements for ECS mem
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
=> fix: ec2 ecs mem (solr) increments based on cpu size

modules/bigeye/locals.tf, modules/bigeye/main.tf, modules/bigeye/variables.tf
This is plumbing environment variables through to the app for Datawatch to make calls to the lineage API service.
=> feat: add datawatch lineageplus config

modules/bigeye/variables.tf
It didn't let me fix the commit message in #521 so this is another attempt.
=> fix: update MC username

modules/bigeye/variables.tf
This bug was introduced in 20.9.0
=> fix: fix monocle cpu validation bug

modules/bigeye/deprecated.tf, modules/bigeye/variables.tf
This will set the default for these features to on.  The flags to control this will then be removed sometime down the road.
Closes SRE-5313 SRE-5166
=> feat: enable EC AZ rebalancing and LB anomaly mitigation by default
